'use client'

import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useRouter } from 'next/navigation'
import { 
  ArrowRight, Loader2, Building2, ArrowLeft, 
  Command, AlertCircle 
} from 'lucide-react'
import Link from 'next/link'
import { cn } from '@/lib/utils'

export default function CreateWorkspace() {
  const [name, setName] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const router = useRouter()
  const supabase = createClient()

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!name.trim()) return
    
    setLoading(true)
    setError('')
    
    try {
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) throw new Error('User not authenticated')

      // 1. Create Workspace
      const { data: workspace, error: wsError } = await supabase
        .from('workspaces')
        .insert({ 
            name: name.trim(), 
            owner_id: user.id,
            // Invite code is auto-generated by DB trigger usually, 
            // or you can generate one here if your schema requires it.
        })
        .select()
        .single()

      if (wsError) throw wsError

      // 2. Add Owner as Member
      const { error: memberError } = await supabase
        .from('workspace_members')
        .insert({ workspace_id: workspace.id, user_id: user.id })

      if (memberError) throw memberError

      // 3. Create 'General' Channel
      const { error: channelError } = await supabase
        .from('channels')
        .insert({ workspace_id: workspace.id, name: 'general', type: 'text' })

      if (channelError) throw channelError

      // 4. Redirect
      router.push('/team-overview') 

    } catch (err) {
      console.error(err)
      const message = err instanceof Error ? err.message : 'Failed to create workspace.'
      setError(message)
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen w-full flex flex-col items-center justify-center p-6 bg-neutral-50 dark:bg-neutral-950 relative overflow-hidden">
      
      {/* Background Decor */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-indigo-500/5 rounded-full blur-3xl pointer-events-none" />

      {/* Navigation (Back) */}
      <div className="absolute top-6 left-6 z-20">
        <Link 
            href="/onboarding"
            className="flex items-center gap-2 text-sm font-medium text-neutral-500 hover:text-neutral-900 dark:hover:text-neutral-100 transition-colors"
        >
            <ArrowLeft className="w-4 h-4" /> Back to Role Selection
        </Link>
      </div>

      <div className="w-full max-w-md relative z-10 animate-in fade-in zoom-in-95 duration-500">
        
        {/* Brand/Logo */}
        <div className="flex justify-center mb-8">
            <div className="bg-white dark:bg-neutral-900 p-3 rounded-2xl shadow-sm border border-neutral-200 dark:border-neutral-800">
                <Command className="w-8 h-8 text-indigo-600 dark:text-indigo-500" />
            </div>
        </div>

        <div className="text-center mb-8">
            <h1 className="text-2xl md:text-3xl font-bold tracking-tight text-neutral-900 dark:text-neutral-50 mb-3">
                Name your Workspace
            </h1>
            <p className="text-neutral-500 dark:text-neutral-400">
                This will be the home base for your team collaboration.
            </p>
        </div>

        <form onSubmit={handleCreate} className="bg-white dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800 rounded-2xl p-6 md:p-8 shadow-sm space-y-6">
            
            {/* Input Field */}
            <div className="space-y-2">
                <label className="text-xs font-bold uppercase tracking-wider text-neutral-500 dark:text-neutral-400 ml-1">
                    Workspace Name
                </label>
                <div className="relative group">
                    <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none">
                        <Building2 className="h-5 w-5 text-neutral-400 group-focus-within:text-indigo-500 transition-colors" />
                    </div>
                    <input
                        autoFocus
                        type="text"
                        placeholder="e.g. Acme Agency"
                        className="block w-full pl-11 pr-4 py-4 bg-neutral-50 dark:bg-neutral-950 border border-neutral-200 dark:border-neutral-800 rounded-xl text-lg font-medium focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 outline-none transition-all placeholder:text-neutral-300 dark:placeholder:text-neutral-700 text-neutral-900 dark:text-neutral-100"
                        value={name}
                        onChange={(e) => setName(e.target.value)}
                        maxLength={50}
                    />
                </div>
                <div className="flex justify-end px-1">
                    <span className="text-[10px] text-neutral-400">{name.length}/50</span>
                </div>
            </div>

            {/* Error Message */}
            {error && (
                <div className="p-3 rounded-lg bg-rose-50 dark:bg-rose-900/20 text-rose-600 dark:text-rose-400 text-sm flex items-center gap-2 animate-in slide-in-from-top-2">
                    <AlertCircle className="w-4 h-4 shrink-0" />
                    {error}
                </div>
            )}

            {/* Submit Button */}
            <button
                type="submit"
                disabled={!name.trim() || loading}
                className={cn(
                    "w-full flex items-center justify-center gap-2 py-3.5 rounded-xl text-white font-semibold shadow-md transition-all",
                    loading 
                        ? "bg-neutral-100 dark:bg-neutral-800 text-neutral-400 cursor-wait shadow-none" 
                        : "bg-indigo-600 hover:bg-indigo-700 hover:shadow-lg hover:-translate-y-0.5"
                )}
            >
                {loading ? (
                    <>
                       <Loader2 className="w-5 h-5 animate-spin" /> Setting up...
                    </>
                ) : (
                    <>
                       Create Workspace <ArrowRight className="w-5 h-5" />
                    </>
                )}
            </button>

            {/* Helper Text */}
            <p className="text-center text-xs text-neutral-400">
                You can change this name later in settings.
            </p>

        </form>
      </div>
    </div>
  )
}